#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: die.exe

die.exe: die.cpp
	$(CC) $(CFLAGS)  die.cpp

clean:
	erase die.exe
