#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: copy2.exe

copy2.exe: copy2.cpp
	$(CC) $(CFLAGS) -D__MSDOS__ copy2.cpp

clean:
	erase copy2.exe
