#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml
all: sqr-i.exe

sqr-i.exe: sqr-i.cpp
	$(CC) $(CFLAGS) -esqr-i sqr-i.cpp

clean:
	erase sqr-i.exe
