#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: comment.exe

comment.exe: comment.cpp
	@echo "This program will not compile due to an error"
	-$(CC) $(CFLAGS)  comment.cpp

clean:
	erase comment.exe
