#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: max.exe stack_c1.exe

max.exe: max.cpp
	$(CC) $(CFLAGS)  max.cpp

stack_c1.exe: stack_c1.cpp
	$(CC) $(CFLAGS)  stack_c1.cpp

words.exe: words.cpp
	$(CC) -v $(CFLAGS)  words.cpp

words.cpp: words.cpp
	$(CC) -E $(CFLAGS) words.cpp>words.cpp

clean:
	erase max.exe stack_c1.exe
