#
# Makefile for many UNIX compilers using the
# "standard" command name CC
#
CC=CC
CFLAGS=-g
all: max stack_c1

max: max.cc
	$(CC) $(CFLAGS) -o max max.cc

stack_c1: stack_c1.cc
	$(CC) $(CFLAGS) -o stack_c1 stack_c1.cc

words: words.cc
	$(CC) -v $(CFLAGS) -o words words.cc

words.cc: words.cc
	$(CC) -E $(CFLAGS) words.cc>words.cc

clean:
	rm max stack_c1
