#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: float2.exe

float2.exe: float2.cpp
	$(CC) $(CFLAGS)  float2.cpp

clean:
	erase float2.exe
