#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: twoc.exe

twoc.exe: twoc.cpp
	$(CC) $(CFLAGS)  twoc.cpp

clean:
	erase twoc.exe
