#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: total2.exe

total2.exe: total2.cpp
	$(CC) $(CFLAGS)  total2.cpp

clean:
	erase total2.exe
