#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: print3.exe

print3.exe: print3.cpp
	$(CC) $(CFLAGS)  print3.cpp

clean:
	erase print3.exe
