#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: words.exe

words.exe: words.cpp
	$(CC) $(CFLAGS)  words.cpp

clean:
	erase words.exe
