#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: array.exe

array.exe: array.cpp
	$(CC) $(CFLAGS)  array.cpp

clean:
	erase array.exe
