#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: perm.exe

perm.exe: perm.cpp
	$(CC) $(CFLAGS)  perm.cpp

clean:
	erase perm.exe
