#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: sam.exe

sam.exe: sam.cpp
	$(CC) $(CFLAGS)  sam.cpp

clean:
	erase sam.exe
