#
# Makefile for many UNIX compilers using the
# "standard" command name CC
#
CC=CC
CFLAGS=-g
class.o: class.cc
	@echo "This does not generate a full program"
	$(CC) $(CFLAGS) -c class.cc

clean:
	rm class.o
