#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: xgets.obj xgets2.obj

xgets.obj: xgets.cpp
	@echo "The following does not generate a full program"
	$(CC) -c $(CFLAGS) xgets.cpp

xgets2.obj: xgets2.cpp
	@echo "The following does not generate a full program"
	$(CC) -c $(CFLAGS) xgets2.cpp

clean:
	erase xgets.obj xgets2.obj
