#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: tmp-name.exe

tmp-name.exe: tmp-name.cpp
	$(CC) $(CFLAGS)  tmp-name.cpp

clean:
	erase tmp-name.exe
