#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
blow.exe: blow.cpp
	$(CC) $(CFLAGS)  blow.cpp

clean:
	erase blow.exe
