#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml
blow.exe: blow.cpp
	$(CC) $(CFLAGS) -eblow blow.cpp

clean:
	erase blow.exe
