#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: calc3.exe

calc3.exe: calc3.cpp
	$(CC) $(CFLAGS)  calc3.cpp

clean.exe:
	erase calc3.exe
