#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
read.exe: read.cpp
	$(CC) $(CFLAGS)  read.cpp

clean:
	erase read.exe
