#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: exp.exe

exp.exe: exp.cpp
	@echo "Expect a null effect warning"
	$(CC) $(CFLAGS)  exp.cpp

clean:
	erase exp.exe
