#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: float.exe

float.exe: float.cpp
	$(CC) $(CFLAGS)  float.cpp

clean:
	erase float.exe
