#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml
all: float.exe

float.exe: float.cpp
	$(CC) $(CFLAGS) -efloat float.cpp

clean:
	erase float.exe
