#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: and.exe

and.exe: and.cpp
	$(CC) $(CFLAGS)  and.cpp

clean:
	erase and.exe
