REM Run this to create files for compiling with Borland-C++
copy and\makefile.bcc and\Makefile
copy array-p\makefile.bcc array-p\Makefile
copy array\makefile.bcc array\Makefile
copy balance\makefile.bcc balance\Makefile
copy base\makefile.bcc base\Makefile
copy big\makefile.bcc big\Makefile
copy blow\makefile.bcc blow\Makefile
copy calc-sw\makefile.bcc calc-sw\Makefile
copy calc1\makefile.bcc calc1\Makefile
copy calc3\makefile.bcc calc3\Makefile
copy cent\makefile.bcc cent\Makefile
copy comment\makefile.bcc comment\Makefile
copy complex\makefile.bcc complex\Makefile
copy cons\makefile.bcc cons\Makefile
copy copy\makefile.bcc copy\Makefile
copy copy2\makefile.bcc copy2\Makefile
copy debug\makefile.bcc debug\Makefile
copy def\makefile.bcc def\Makefile
copy die\makefile.bcc die\Makefile
copy die3\makefile.bcc die3\Makefile
copy doit\makefile.bcc doit\Makefile
copy double\makefile.bcc double\Makefile
copy equal\makefile.bcc equal\Makefile
copy exp\makefile.bcc exp\Makefile
copy fib\makefile.bcc fib\Makefile
copy find\makefile.bcc find\Makefile
copy first\makefile.bcc first\Makefile
copy five\makefile.bcc five\Makefile
copy float\makefile.bcc float\Makefile
copy float1\makefile.bcc float1\Makefile
copy float2\makefile.bcc float2\Makefile
copy float3\makefile.bcc float3\Makefile
copy fun-file\makefile.bcc fun-file\Makefile
copy graph\makefile.bcc graph\Makefile
copy guess\makefile.bcc guess\Makefile
copy hello\makefile.bcc hello\Makefile
copy hello2\makefile.bcc hello2\Makefile
copy ia\makefile.bcc ia\Makefile
copy init-a\makefile.bcc init-a\Makefile
copy io\makefile.bcc io\Makefile
copy len\makefile.bcc len\Makefile
copy length\makefile.bcc length\Makefile
copy loop\makefile.bcc loop\Makefile
copy matrix\makefile.bcc matrix\Makefile
copy max-t\makefile.bcc max-t\Makefile
copy max\makefile.bcc max\Makefile
copy name2\makefile.bcc name2\Makefile
copy not2\makefile.bcc not2\Makefile
copy perm\makefile.bcc perm\Makefile
copy print\makefile.bcc print\Makefile
copy print3\makefile.bcc print3\Makefile
copy ptr2\makefile.bcc ptr2\Makefile
copy read\makefile.bcc read\Makefile
copy rec\makefile.bcc rec\Makefile
copy ref\makefile.bcc ref\Makefile
copy search\makefile.bcc search\Makefile
copy seven\makefile.bcc seven\Makefile
copy sin\makefile.bcc sin\Makefile
copy size\makefile.bcc size\Makefile
copy split\makefile.bcc split\Makefile
copy sqr-i\makefile.bcc sqr-i\Makefile
copy sqr\makefile.bcc sqr\Makefile
copy stack_c\makefile.bcc stack_c\Makefile
copy stack_s\makefile.bcc stack_s\Makefile
copy stat\makefile.bcc stat\Makefile
copy str\makefile.bcc str\Makefile
copy tf\makefile.bcc tf\Makefile
copy thing\makefile.bcc thing\Makefile
copy tmp-name\makefile.bcc tmp-name\Makefile
copy tmp2\makefile.bcc tmp2\Makefile
copy total\makefile.bcc total\Makefile
copy total2\makefile.bcc total2\Makefile
copy total6\makefile.bcc total6\Makefile
copy tri\makefile.bcc tri\Makefile
copy tterm\makefile.bcc tterm\Makefile
copy two\makefile.bcc two\Makefile
copy two2\makefile.bcc two2\Makefile
copy value\makefile.bcc value\Makefile
copy virt\makefile.bcc virt\Makefile
copy wbin\makefile.bcc wbin\Makefile
copy words\makefile.bcc words\Makefile
copy xgets\makefile.bcc xgets\Makefile
