REM Run this to create files for compiling with Microsoft Visual-C++
copy and\makefile.msc and\Makefile
copy array-p\makefile.msc array-p\Makefile
copy array\makefile.msc array\Makefile
copy balance\makefile.msc balance\Makefile
copy base\makefile.msc base\Makefile
copy big\makefile.msc big\Makefile
copy blow\makefile.msc blow\Makefile
copy calc-sw\makefile.msc calc-sw\Makefile
copy calc1\makefile.msc calc1\Makefile
copy calc3\makefile.msc calc3\Makefile
copy cent\makefile.msc cent\Makefile
copy comment\makefile.msc comment\Makefile
copy complex\makefile.msc complex\Makefile
copy cons\makefile.msc cons\Makefile
copy copy\makefile.msc copy\Makefile
copy copy2\makefile.msc copy2\Makefile
copy debug\makefile.msc debug\Makefile
copy def\makefile.msc def\Makefile
copy die\makefile.msc die\Makefile
copy die3\makefile.msc die3\Makefile
copy doit\makefile.msc doit\Makefile
copy double\makefile.msc double\Makefile
copy equal\makefile.msc equal\Makefile
copy exp\makefile.msc exp\Makefile
copy fib\makefile.msc fib\Makefile
copy find\makefile.msc find\Makefile
copy first\makefile.msc first\Makefile
copy five\makefile.msc five\Makefile
copy float\makefile.msc float\Makefile
copy float1\makefile.msc float1\Makefile
copy float2\makefile.msc float2\Makefile
copy float3\makefile.msc float3\Makefile
copy fun-file\makefile.msc fun-file\Makefile
copy graph\makefile.msc graph\Makefile
copy guess\makefile.msc guess\Makefile
copy hello\makefile.msc hello\Makefile
copy hello2\makefile.msc hello2\Makefile
copy ia\makefile.msc ia\Makefile
copy init-a\makefile.msc init-a\Makefile
copy io\makefile.msc io\Makefile
copy len\makefile.msc len\Makefile
copy length\makefile.msc length\Makefile
copy loop\makefile.msc loop\Makefile
copy matrix\makefile.msc matrix\Makefile
copy max-t\makefile.msc max-t\Makefile
copy max\makefile.msc max\Makefile
copy name2\makefile.msc name2\Makefile
copy not2\makefile.msc not2\Makefile
copy perm\makefile.msc perm\Makefile
copy print\makefile.msc print\Makefile
copy print3\makefile.msc print3\Makefile
copy ptr2\makefile.msc ptr2\Makefile
copy read\makefile.msc read\Makefile
copy rec\makefile.msc rec\Makefile
copy ref\makefile.msc ref\Makefile
copy search\makefile.msc search\Makefile
copy seven\makefile.msc seven\Makefile
copy sin\makefile.msc sin\Makefile
copy size\makefile.msc size\Makefile
copy split\makefile.msc split\Makefile
copy sqr-i\makefile.msc sqr-i\Makefile
copy sqr\makefile.msc sqr\Makefile
copy stack_c\makefile.msc stack_c\Makefile
copy stack_s\makefile.msc stack_s\Makefile
copy stat\makefile.msc stat\Makefile
copy str\makefile.msc str\Makefile
copy tf\makefile.msc tf\Makefile
copy thing\makefile.msc thing\Makefile
copy tmp-name\makefile.msc tmp-name\Makefile
copy tmp2\makefile.msc tmp2\Makefile
copy total\makefile.msc total\Makefile
copy total2\makefile.msc total2\Makefile
copy total6\makefile.msc total6\Makefile
copy tri\makefile.msc tri\Makefile
copy tterm\makefile.msc tterm\Makefile
copy two\makefile.msc two\Makefile
copy two2\makefile.msc two2\Makefile
copy value\makefile.msc value\Makefile
copy virt\makefile.msc virt\Makefile
copy wbin\makefile.msc wbin\Makefile
copy words\makefile.msc words\Makefile
copy xgets\makefile.msc xgets\Makefile
