REM Run this to create files for compiling with Turbo-C++
copy and\makefile.tcc and\Makefile
copy array-p\makefile.tcc array-p\Makefile
copy array\makefile.tcc array\Makefile
copy balance\makefile.tcc balance\Makefile
copy base\makefile.tcc base\Makefile
copy big\makefile.tcc big\Makefile
copy blow\makefile.tcc blow\Makefile
copy calc-sw\makefile.tcc calc-sw\Makefile
copy calc1\makefile.tcc calc1\Makefile
copy calc3\makefile.tcc calc3\Makefile
copy cent\makefile.tcc cent\Makefile
copy comment\makefile.tcc comment\Makefile
copy complex\makefile.tcc complex\Makefile
copy cons\makefile.tcc cons\Makefile
copy copy\makefile.tcc copy\Makefile
copy copy2\makefile.tcc copy2\Makefile
copy debug\makefile.tcc debug\Makefile
copy def\makefile.tcc def\Makefile
copy die\makefile.tcc die\Makefile
copy die3\makefile.tcc die3\Makefile
copy doit\makefile.tcc doit\Makefile
copy double\makefile.tcc double\Makefile
copy equal\makefile.tcc equal\Makefile
copy exp\makefile.tcc exp\Makefile
copy fib\makefile.tcc fib\Makefile
copy find\makefile.tcc find\Makefile
copy first\makefile.tcc first\Makefile
copy five\makefile.tcc five\Makefile
copy float\makefile.tcc float\Makefile
copy float1\makefile.tcc float1\Makefile
copy float2\makefile.tcc float2\Makefile
copy float3\makefile.tcc float3\Makefile
copy fun-file\makefile.tcc fun-file\Makefile
copy graph\makefile.tcc graph\Makefile
copy guess\makefile.tcc guess\Makefile
copy hello\makefile.tcc hello\Makefile
copy hello2\makefile.tcc hello2\Makefile
copy ia\makefile.tcc ia\Makefile
copy init-a\makefile.tcc init-a\Makefile
copy io\makefile.tcc io\Makefile
copy len\makefile.tcc len\Makefile
copy length\makefile.tcc length\Makefile
copy loop\makefile.tcc loop\Makefile
copy matrix\makefile.tcc matrix\Makefile
copy max-t\makefile.tcc max-t\Makefile
copy max\makefile.tcc max\Makefile
copy name2\makefile.tcc name2\Makefile
copy not2\makefile.tcc not2\Makefile
copy perm\makefile.tcc perm\Makefile
copy print\makefile.tcc print\Makefile
copy print3\makefile.tcc print3\Makefile
copy ptr2\makefile.tcc ptr2\Makefile
copy read\makefile.tcc read\Makefile
copy rec\makefile.tcc rec\Makefile
copy ref\makefile.tcc ref\Makefile
copy search\makefile.tcc search\Makefile
copy seven\makefile.tcc seven\Makefile
copy sin\makefile.tcc sin\Makefile
copy size\makefile.tcc size\Makefile
copy split\makefile.tcc split\Makefile
copy sqr-i\makefile.tcc sqr-i\Makefile
copy sqr\makefile.tcc sqr\Makefile
copy stack_c\makefile.tcc stack_c\Makefile
copy stack_s\makefile.tcc stack_s\Makefile
copy stat\makefile.tcc stat\Makefile
copy str\makefile.tcc str\Makefile
copy tf\makefile.tcc tf\Makefile
copy thing\makefile.tcc thing\Makefile
copy tmp-name\makefile.tcc tmp-name\Makefile
copy tmp2\makefile.tcc tmp2\Makefile
copy total\makefile.tcc total\Makefile
copy total2\makefile.tcc total2\Makefile
copy total6\makefile.tcc total6\Makefile
copy tri\makefile.tcc tri\Makefile
copy tterm\makefile.tcc tterm\Makefile
copy two\makefile.tcc two\Makefile
copy two2\makefile.tcc two2\Makefile
copy value\makefile.tcc value\Makefile
copy virt\makefile.tcc virt\Makefile
copy wbin\makefile.tcc wbin\Makefile
copy words\makefile.tcc words\Makefile
copy xgets\makefile.tcc xgets\Makefile
