#
# Makefile for many UNIX compilers using the
# "standard" command name CC
#
CC=CC
CFLAGS=-g
all: ptr2 ptr2a

ptr2a: ptr2a.cc
	$(CC) $(CFLAGS) -o ptr2a ptr2a.cc

ptr2: ptr2.cc
	$(CC) $(CFLAGS) -o ptr2 ptr2.cc

clean:
	rm ptr2 ptr2a
