#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: def.exe

def.exe: def.cpp
	$(CC) $(CFLAGS)  def.cpp

clean:
	erase def.exe
