#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
hello2.exe: hello2.cpp
	$(CC) $(CFLAGS)  hello2.cpp

clean:
	erase hello2.exe
