#
# Makefile for many UNIX compilers using the
# "standard" command name CC
#
C_COMPILE=cc
CFLAGS=-g

fun-file: fun-file.c
	$(C_COMPILE) $(CFLAGS) -o fun-file fun-file.c

clean:
	rm fun-file
