#
# Makefile for many UNIX compilers using the
# "standard" command name CC
#
CC=CC
CFLAGS=-g
doit_t: doit_t.cc
	@echo "This compile generates an error"
	-$(CC) $(CFLAGS) -o doit_t doit_t.cc

clean:
	rm doit_t
