#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: size.exe

size.exe: size.cpp
	$(CC) $(CFLAGS)  size.cpp

clean:
	erase size.exe
