#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: cent.exe

cent.exe: cent.cpp
	$(CC) $(CFLAGS)  cent.cpp

clean:
	erase cent.exe

