#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: total.exe

total.exe: total.cpp
	$(CC) $(CFLAGS)  total.cpp

clean:
	erase total.exe
