#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: tri.exe

tri.exe: tri.cpp
	$(CC) $(CFLAGS)  tri.cpp

clean:
	erase tri.exe
