#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: split.exe

split.exe: split.cpp
	$(CC) $(CFLAGS)  split.cpp

clean:
	erase split.exe
