#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
virt.exe: virt.cpp
	$(CC) $(CFLAGS)  virt.cpp

clean:
	erase virt.exe
