#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: thing.exe

thing.exe: thing.cpp
	$(CC) $(CFLAGS)  thing.cpp

clean:
	erase thing.exe
