#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
sine.exe: sine.cpp
	$(CC) $(CFLAGS)  sine.cpp 

clean:
	erase sine.exe
