#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: total6.exe total6w.exe

total6.exe: total6.cpp
	$(CC) $(CFLAGS)  total6.cpp

total6w.exe: total6w.cpp
	$(CC) $(CFLAGS)  total6w.cpp

clean:
	erase total6.exe total6w.exe
