#
# Makefile for many UNIX compilers using the
# "standard" command name CC
#
CC=CC
CFLAGS=-g
all: big

big: big.cc
	@echo The following compile generates a syntax error
	$(CC) $(CFLAGS) -o big big.cc

clean:
	rm big
