#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: five.exe

five.exe: five.cpp
	$(CC) $(CFLAGS)  five.cpp

clean:
	erase five.exe
