#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: graph.exe

graph.exe: graph.cpp
	$(CC) $(CFLAGS)  graph.cpp

clean:
	erase graph.exe
