#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: fib.exe

fib.exe: fib.cpp
	$(CC) $(CFLAGS)  fib.cpp

clean:
	erase fib.exe
