#
# Makefile for many UNIX compilers using the
# "standard" command name CC
#
CC=CC
CFLAGS=-g
all: float1

float1: float1.cc
	@echo "This program will generate a warning when compiled"
	$(CC) $(CFLAGS) -o float1 float1.cc

clean:
	rm float1
