#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: double.exe

double.exe: double.cpp
	$(CC) $(CFLAGS)  double.cpp

clean:
	erase double.exe
