#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: print.exe

print.exe: print.cpp
	$(CC) $(CFLAGS)  print.cpp

clean:
	erase print.exe
