#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: wbin.exe

wbin.exe: wbin.cpp
	$(CC) $(CFLAGS)  wbin.cpp

clean:
	erase wbin.exe
