#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: len.exe

len.exe: len.cpp
	$(CC) $(CFLAGS)  len.cpp

clean:
	erase len.exe
