#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: flush.exe cstop.obj flush2.exe

flush.exe: flush.cpp
	$(CC) $(CFLAGS)  flush.cpp

flush2.exe: flush2.cpp
	$(CC) $(CFLAGS)  flush2.cpp

cstop.obj: cstop.cpp
	@echo "Generates object file only"
	$(CC) $(CFLAGS) -c cstop.cpp

clean:
	erase flush.exe cstop.obj flush2.exe
