#
# Makefile for many UNIX compilers using the
# "standard" command name CC
#
CC=CC
CFLAGS=-g
all: flush cstop.o flush2

flush: flush.cc
	$(CC) $(CFLAGS) -o flush flush.cc

flush2: flush2.cc
	$(CC) $(CFLAGS) -o flush2 flush2.cc

cstop.o: cstop.cc
	@echo "Generates object file only"
	$(CC) $(CFLAGS) -c cstop.cc

clean: 
	rm flush cstop.o flush2
