#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
loop.exe: loop.cpp
	$(CC) $(CFLAGS)  loop.cpp

clean:
	erase loop.exe
