#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
equal.exe: equal.cpp
	$(CC) $(CFLAGS)  equal.cpp

clean:
	erase equal.exe
