#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml
equal.exe: equal.cpp
	$(CC) $(CFLAGS) -eequal equal.cpp

clean:
	erase equal.exe
