#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: find.obj

find.obj: find.cpp
	$(CC) -c $(CFLAGS) find.cpp

clean:
	erase find.obj
