#
# Makefile for Microsoft Visual C++
#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1
all: value.exe ref.exe big.obj

big.obj: big.cpp
	$(CC) $(CFLAGS) -c big.cpp

value.exe: value.cpp
	$(CC) $(CFLAGS)  value.cpp

ref.exe: ref.cpp
	$(CC) $(CFLAGS)  ref.cpp

clean:
	erase big.obj value.exe ref.exe
	
